
create table QUESTION(
	Q_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	TITLE TEXT not null,
	QUESTION TEXT not null
	);

create table CHOICES(
	Q_ID INTEGER not null,
	C_NUMBER INTEGER not null,
	TEXT TEXT not null,
    POINT INTEGER,
	CONSTRAINT CHOICES_FK FOREIGN KEY(Q_ID)
	REFERENCES QUESTION(Q_ID)
	PRIMARY KEY(Q_ID, C_NUMBER)
	);